version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MYSQL_HOST=db
      - MYSQL_USER=interview_user
      - MYSQL_PASSWORD=interview_password
      - MYSQL_DATABASE=interview_agent
      - FLASK_ENV=production
    depends_on:
      - db
    volumes:
      - .:/app
    command: python app.py

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=interview_agent
      - MYSQL_USER=interview_user
      - MYSQL_PASSWORD=interview_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: